-- Enable PostGIS extension for spatial queries
create extension if not exists postgis;

-- Create the places table
create table if not exists places (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  city text,
  category text,
  latitude float not null,
  longitude float not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Add a spatial column for efficient querying
  location geography(POINT) generated always as (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) stored
);

-- Create a spatial index
create index if not exists places_location_idx on places using GIST (location);

-- Create the RPC function for radius search
create or replace function places_within_radius(center_lat float, center_lng float, radius_km float)
returns table (
  id bigint,
  name text,
  description text,
  city text,
  category text,
  latitude float,
  longitude float,
  dist_km float
)
language sql
as $$
  select 
    id,
    name,
    description,
    city,
    category,
    latitude,
    longitude,
    (ST_Distance(location, ST_SetSRID(ST_MakePoint(center_lng, center_lat), 4326)::geography) / 1000) as dist_km
  from places
  where ST_DWithin(location, ST_SetSRID(ST_MakePoint(center_lng, center_lat), 4326)::geography, radius_km * 1000)
  order by dist_km;
$$;